#This uses endpoints for crop and robots in src/PresentationAPI/EndPoints
//For Render cloud connections
//'@' defines a variable
@baseaddress = https://automated-greenhouse.onrender.com
//For local host connections
# @baseAddress = http://localhost:5242
###__ROBOT__##
# inject varaible
POST {{baseaddress}}/robots
content-type: application/json

{
   "name": "R2"
}

###Three markers are needed to separate requests

GET {{baseaddress}}/robots

###
#/robots/id_to_delete
DELETE {{baseaddress}}/robots/2

###__CROP__##

POST {{baseaddress}}/crops
content-type: application/json

 {
    "name": "Orange"
 }

###
# Get all crops
GET {{baseaddress}}/crops

###
#this was early test, no longer used
POST {{baseaddress}}/robots/1/water/1

###
#/crops/id_to_delete
DELETE {{baseaddress}}/crops/1
